import 'package:flutter/material.dart';
import 'package:passgeni/Constans/Reusable%20Widgets/text.dart';

import '../../../Constans/App Colors/appColors.dart';

class faqScreen extends StatefulWidget {
  const faqScreen({super.key});

  @override
  State<faqScreen> createState() => _faqScreenState();
}

class _faqScreenState extends State<faqScreen> {

  @override
  Widget build(BuildContext context) {
    final height = MediaQuery.of(context).size.height;
    final width = MediaQuery.of(context).size.width;
    return Scaffold(
      backgroundColor: appColors.bgColor,
      appBar: AppBar(
        scrolledUnderElevation: 0,
        backgroundColor: appColors.bgColor,
        leading: InkWell(
            onTap: (){
              Navigator.pop(context);
            },
            child: Icon(
              Icons.arrow_back_ios_outlined,
              size: 25,
              color: appColors.iconsColor,
            )
        ),
      ),
      body: Padding(
        padding: EdgeInsets.symmetric(horizontal: width*0.06),
        child: SingleChildScrollView(
          child: Column(
            children: [

              Align(
                alignment: Alignment.topLeft,
                child: text(data: 'Frequently Asked Questions(FAQ)', fs: 15, textColor: const Color(0xffF4F4F4), fw: FontWeight.w900),
              ),
              SizedBox(
                height: height*0.006,
              ),
              Align(
                alignment: Alignment.topLeft,
                child: text(data: "Questions about this random password generator? Answers below!", fs: 14, textColor: appColors.text2Color, fw: FontWeight.w600),
              ),

              ExpansionTile(
                backgroundColor: Colors.transparent,
                iconColor: const Color(0xffF4F4F4),
                collapsedIconColor: const Color(0xffF4F4F4),
                title: Align(
                  alignment: Alignment.centerLeft,
                  child: text(
                    data: 'Is PassGeni safe to use?',
                    fs: 15,
                    textColor: const Color(0xffF4F4F4),
                    fw: FontWeight.w700,
                  ),
                ),
                collapsedBackgroundColor: Colors.transparent,
                collapsedShape: const RoundedRectangleBorder(
                  side: BorderSide(color: Colors.transparent),
                ),
                shape: const RoundedRectangleBorder(
                  side: BorderSide(color: Colors.transparent),
                ),
                children: [
                  Padding(
                    padding: const EdgeInsets.symmetric(horizontal: 16.0),
                    child: Align(
                      alignment: Alignment.centerLeft,
                      child: text(
                        data: "Absolutely! All passwords you create with Passgeni are generated by OpenAI in your browser on your computer. They are not saved or shared anywhere, even Passgeni can't see your password. Just be sure to close this page once you’ve generated and copied your password to prevent anyone else from seeing it if they use your computer.",
                        fs: 14,
                        textColor: appColors.text2Color,
                        fw: FontWeight.w400,
                      ),
                    ),
                  ),
                ],
              ),
              ExpansionTile(
                backgroundColor: Colors.transparent,
                iconColor: const Color(0xffF4F4F4),
                collapsedIconColor: const Color(0xffF4F4F4),
                title: Align(
                  alignment: Alignment.centerLeft,
                  child: text(
                    data: 'Do I need a unique password for every account?',
                    fs: 15,
                    textColor: const Color(0xffF4F4F4),
                    fw: FontWeight.w700,
                  ),
                ),
                collapsedBackgroundColor: Colors.transparent,
                collapsedShape: const RoundedRectangleBorder(
                  side: BorderSide(color: Colors.transparent),
                ),
                shape: const RoundedRectangleBorder(
                  side: BorderSide(color: Colors.transparent),
                ),
                children: [
                  Padding(
                    padding: const EdgeInsets.symmetric(horizontal: 16.0),
                    child: Align(
                      alignment: Alignment.centerLeft,
                      child: text(
                        data: "100%, Using the same password across multiple accounts is a huge no-no. If hackers learn the password to one of your accounts, they’ll have your password for all the others, too. So make sure you use a unique password for each account.",
                        fs: 14,
                        textColor: appColors.text2Color,
                        fw: FontWeight.w400,
                      ),
                    ),
                  ),
                ],
              ),
              ExpansionTile(
                backgroundColor: Colors.transparent,
                iconColor: const Color(0xffF4F4F4),
                collapsedIconColor: const Color(0xffF4F4F4),
                title: Align(
                  alignment: Alignment.centerLeft,
                  child: text(
                    data: 'What is the difference between a Random password and memorable passwords?',
                    fs: 15,
                    textColor: const Color(0xffF4F4F4),
                    fw: FontWeight.w700,
                  ),
                ),
                collapsedBackgroundColor: Colors.transparent,
                collapsedShape: const RoundedRectangleBorder(
                  side: BorderSide(color: Colors.transparent),
                ),
                shape: const RoundedRectangleBorder(
                  side: BorderSide(color: Colors.transparent),
                ),
                children: [
                  Padding(
                    padding: const EdgeInsets.symmetric(horizontal: 16.0),
                    child: Align(
                      alignment: Alignment.centerLeft,
                      child: text(
                        data: "Memorable passwords or 'passphrases' are typically a combination of 3-6 words strung together into a mnemonic device. Because passphrases are often over 20 characters or longer, they are extremely resilient to brute force attacks, but also easy to recall compared to a random string of 20 characters.",
                        fs: 14,
                        textColor: appColors.text2Color,
                        fw: FontWeight.w400,
                      ),
                    ),
                  ),
                ],
              ),
              ExpansionTile(
                backgroundColor: Colors.transparent,
                iconColor: const Color(0xffF4F4F4),
                collapsedIconColor: const Color(0xffF4F4F4),
                title: Align(
                  alignment: Alignment.centerLeft,
                  child: text(
                    data: 'How does AI assist in creating unique and complex passwords?',
                    fs: 15,
                    textColor: const Color(0xffF4F4F4),
                    fw: FontWeight.w700,
                  ),
                ),
                collapsedBackgroundColor: Colors.transparent,
                collapsedShape: const RoundedRectangleBorder(
                  side: BorderSide(color: Colors.transparent),
                ),
                shape: const RoundedRectangleBorder(
                  side: BorderSide(color: Colors.transparent),
                ),
                children: [
                  Padding(
                    padding: const EdgeInsets.symmetric(horizontal: 16.0),
                    child: Align(
                      alignment: Alignment.centerLeft,
                      child: text(
                        data: "AI utilizes advanced algorithms to generate passwords that are both unique and complex, making it extremely challenging for cybercriminals to crack them.",
                        fs: 14,
                        textColor: appColors.text2Color,
                        fw: FontWeight.w400,
                      ),
                    ),
                  ),
                ],
              ),
              ExpansionTile(
                backgroundColor: Colors.transparent,
                iconColor: const Color(0xffF4F4F4),
                collapsedIconColor: const Color(0xffF4F4F4),
                title: Align(
                  alignment: Alignment.centerLeft,
                  child: text(
                    data: 'Are AI-generated passwords easier to remember?',
                    fs: 15,
                    textColor: const Color(0xffF4F4F4),
                    fw: FontWeight.w700,
                  ),
                ),
                collapsedBackgroundColor: Colors.transparent,
                collapsedShape: const RoundedRectangleBorder(
                  side: BorderSide(color: Colors.transparent),
                ),
                shape: const RoundedRectangleBorder(
                  side: BorderSide(color: Colors.transparent),
                ),
                children: [
                  Padding(
                    padding: const EdgeInsets.symmetric(horizontal: 16.0),
                    child: Align(
                      alignment: Alignment.centerLeft,
                      child: text(
                        data: "Yes, AI takes into account memorability, crafting passphrases or passwords that are easier to recall while still meeting security standards.",
                        fs: 14,
                        textColor: appColors.text2Color,
                        fw: FontWeight.w400,
                      ),
                    ),
                  ),
                ],
              ),
              ExpansionTile(
                backgroundColor: Colors.transparent,
                iconColor: const Color(0xffF4F4F4),
                collapsedIconColor: const Color(0xffF4F4F4),
                title: Align(
                  alignment: Alignment.centerLeft,
                  child: text(
                    data: 'How can AI benefit businesses in terms of password security?',
                    fs: 15,
                    textColor: const Color(0xffF4F4F4),
                    fw: FontWeight.w700,
                  ),
                ),
                collapsedBackgroundColor: Colors.transparent,
                collapsedShape: const RoundedRectangleBorder(
                  side: BorderSide(color: Colors.transparent),
                ),
                shape: const RoundedRectangleBorder(
                  side: BorderSide(color: Colors.transparent),
                ),
                children: [
                  Padding(
                    padding: const EdgeInsets.symmetric(horizontal: 16.0),
                    child: Align(
                      alignment: Alignment.centerLeft,
                      child: text(
                        data: "AI-powered password solutions enhance security by generating strong passwords, managing them efficiently, and regularly assessing their strength, all for free. This reduces the risk of data breaches and ensures that employees maintain robust password practices.",
                        fs: 14,
                        textColor: appColors.text2Color,
                        fw: FontWeight.w400,
                      ),
                    ),
                  ),
                ],
              ),
              ExpansionTile(
                backgroundColor: Colors.transparent,
                iconColor: const Color(0xffF4F4F4),
                collapsedIconColor: const Color(0xffF4F4F4),
                title: Align(
                  alignment: Alignment.centerLeft,
                  child: text(
                    data: 'Are AI-driven password management tools user-friendly?',
                    fs: 15,
                    textColor: const Color(0xffF4F4F4),
                    fw: FontWeight.w700,
                  ),
                ),
                collapsedBackgroundColor: Colors.transparent,
                collapsedShape: const RoundedRectangleBorder(
                  side: BorderSide(color: Colors.transparent),
                ),
                shape: const RoundedRectangleBorder(
                  side: BorderSide(color: Colors.transparent),
                ),
                children: [
                  Padding(
                    padding: const EdgeInsets.symmetric(horizontal: 16.0),
                    child: Align(
                      alignment: Alignment.centerLeft,
                      child: text(
                        data: "Yes, these tools are designed with user-friendliness in mind. They simplify password management, often providing features like automatic password generation and one-click login for ease of use.",
                        fs: 14,
                        textColor: appColors.text2Color,
                        fw: FontWeight.w400,
                      ),
                    ),
                  ),
                ],
              ),

            ],
          ),
        ),
      ),
    );
  }
}
